#!/usr/bin/env Rscript
library(vcfR)
library(StAMPP)
library(poppr)
library(adegenet)
library(phytools)
library(ape)
vcf <- read.vcfR("somaticMutation_nh.vcf")
aa.genlight <- vcfR2genlight(vcf, n.cores=1)
ploidy(aa.genlight) <- "2"

customdist <- function(x) bitwise.dist(x, percent = FALSE)
bootstrap <-aboot(aa.genlight, tree = "nj", distance = customdist, sample = 1000, missing = "ignore")
pdf("tree_01.pdf", width = 6, height = 6)
plot.phylo(bootstrap, type = "phylogram", show.tip = TRUE, show.node.label = TRUE, cex = 0.6)
dev.off()

pdf("tree_02.pdf",width=6,height=6)
plot.phylo(bootstrap, type = "unrooted", show.tip = FALSE, show.node.label = FALSE)
add.scale.bar(800,200,cex = 1, font = 2, length = 100, lwd = 2)


tiplabels(text = "1", tip = 1, adj = c(1.25, 0), col = "green", frame = "none")
tiplabels(text = "2", tip = 2, adj = c(-0.5, 1), col = "green", frame = "none")
tiplabels(text = "3", tip = 3, adj = c(1, 0), col = "green", frame = "none")
tiplabels(text = "4", tip = 4, adj = c(0.5, -0.5), col = "green", frame = "none")
tiplabels(text = "5", tip = 5, adj = c(0, 0), col = "green", frame = "none")
tiplabels(text = "6", tip = 6, adj = c(1, 0.5), col = "green", frame = "none")
tiplabels(text = "7", tip = 7, adj = c(0, 0), col = "green", frame = "none")
tiplabels(text = "8", tip = 8, adj = c(0, 1), col = "green", frame = "none")
tiplabels(text = "9", tip = 9, adj = c(0, 0), col = "green", frame = "none")
tiplabels(text = "10", tip = 10, adj = c(0, 0), col = "green", frame = "none")
tiplabels(text = "11", tip = 11, adj = c(0, 1), col = "green", frame = "none")
tiplabels(text = "12", tip = 12, adj = c(1, 1), col = "green", frame = "none")

tiplabels(text = "13", tip = 13, adj = c(1, 0), col = "blue", frame = "none")
tiplabels(text = "14", tip = 14, adj = c(1, 0), col = "blue", frame = "none")
tiplabels(text = "15", tip = 15, adj = c(0, 0), col = "blue", frame = "none")
tiplabels(text = "16", tip = 16, adj = c(1, 0), col = "blue", frame = "none")
tiplabels(text = "17", tip = 17, adj = c(0, 0), col = "blue", frame = "none")
tiplabels(text = "18", tip = 18, adj = c(1, -0.5), col = "blue", frame = "none")
tiplabels(text = "19", tip = 19, adj = c(2, 0.5), col = "blue", frame = "none")
tiplabels(text = "20", tip = 20, adj = c(1, 0), col = "blue", frame = "none")
tiplabels(text = "21", tip = 21, adj = c(2, 2), col = "blue", frame = "none")
tiplabels(text = "22", tip = 22, adj = c(0, 0), col = "blue", frame = "none")
tiplabels(text = "23", tip = 23, adj = c(1, 1.5), col = "blue", frame = "none")
tiplabels(text = "24", tip = 24, adj = c(1, 1), col = "blue", frame = "none")

legend(400,1300, legend = c("Samples from deep water (~4m)", "Samples from shallow water (~2m)"), text.col = c("blue", "green"))
dev.off()
